openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    get:
      summary: Get all users.
      description: Returns list of users aggregated from configured data sources. Optional filters may be applied.
      operationId: getUsers
      parameters:
        - name: id
          in: query
          description: User id filter.
          required: false
          schema:
            type: string
        - name: username
          in: query
          description: Username filter.
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Name filter.
          required: false
          schema:
            type: string
        - name: surname
          in: query
          description: Surname filter.
          required: false
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        surname:
          type: string
      example:
        id: 1
        username: Username
        name: Name
        surname: Surname